### ISSUE TITLE
_waitHandle vs _waitHandleAlt

### ISSUE THREAD

**Issue by jeffrson** [lordofduct/spacepuppy-unity-framework#5]
Yes, I know there is a newer version of InvokePump - but I wonder what the purpose of _waitHandle and _waitHandleAlt had been. Could you elaborate?

**Comment by lordofduct** [comment]
OK, so you'll notice I only commented it out. This is because I wasn't sure if the new version would work correctly... and honestly, now thinking about it, the new version is flawed as well.

So in the original version it was intended to deal with when someone called Invoke from within the method that was Invoked in the first place. (think like adding/removing an event listender during the method handling said event).

Does it get called immediately? Does it wait for next frame? How does the WaitHandle block?

It's supposed to allow waiting until the next frame, and the thread that called Invoke blocks appropriately.

The new version... if I'm thinking about this correctly (sorry, just woke up), might not actually be blocking correctly anymore. Darn it... I'll have to run some tests.

**Comment by lordofduct** [comment]
That's right... sorry, I'm back.

I have it setup so that you can't even call Invoke from the same thread that it would Invoke onto (basically you can't call Invoke in the callback of an Invoke).

Thusly making the 2 wait handle's unnecessary, so I removed the second.

Sorry... had to wake up and think about it for a second.
